"""Frozen prototype baseline."""
from alembic import op
import sqlalchemy as sa
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('src_id', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=60), nullable=False),
    sa.Column('dst_id', sa.String(length=32), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=True),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_edges_dst_id'), 'access_edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_access_edges_relation'), 'access_edges', ['relation'], unique=False)
    op.create_index(op.f('ix_access_edges_source_id'), 'access_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_access_edges_src_id'), 'access_edges', ['src_id'], unique=False)
    op.create_index(op.f('ix_access_edges_tenant_id'), 'access_edges', ['tenant_id'], unique=False)
    op.create_table('access_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=True),
    sa.Column('external_id', sa.String(length=300), nullable=True),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'name')
    )
    op.create_index(op.f('ix_access_nodes_external_id'), 'access_nodes', ['external_id'], unique=False)
    op.create_index(op.f('ix_access_nodes_kind'), 'access_nodes', ['kind'], unique=False)
    op.create_index(op.f('ix_access_nodes_name'), 'access_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_access_nodes_source_id'), 'access_nodes', ['source_id'], unique=False)
    op.create_index(op.f('ix_access_nodes_tenant_id'), 'access_nodes', ['tenant_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('required_capability', sa.String(length=120), nullable=False),
    sa.Column('justification', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approver', sa.String(length=200), nullable=True),
    sa.Column('approver_path', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_correlation_id'), 'approvals', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_table('audit_records',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('access_path', sa.JSON(), nullable=True),
    sa.Column('policy_input', sa.JSON(), nullable=True),
    sa.Column('policy_decision', sa.JSON(), nullable=True),
    sa.Column('policy_version', sa.String(length=60), nullable=True),
    sa.Column('approval', sa.JSON(), nullable=True),
    sa.Column('grant', sa.JSON(), nullable=True),
    sa.Column('api_calls', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('prev_hash')
    )
    op.create_index(op.f('ix_audit_records_action'), 'audit_records', ['action'], unique=False)
    op.create_index(op.f('ix_audit_records_correlation_id'), 'audit_records', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_records_event'), 'audit_records', ['event'], unique=False)
    op.create_index(op.f('ix_audit_records_subject'), 'audit_records', ['subject'], unique=False)
    op.create_index(op.f('ix_audit_records_tenant_id'), 'audit_records', ['tenant_id'], unique=False)
    op.create_table('grants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('session_tags', sa.JSON(), nullable=False),
    sa.Column('broker_kind', sa.String(length=40), nullable=False),
    sa.Column('credential_ref', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grants_correlation_id'), 'grants', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_grants_subject'), 'grants', ['subject'], unique=False)
    op.create_index(op.f('ix_grants_tenant_id'), 'grants', ['tenant_id'], unique=False)
    op.create_table('ingest_receipts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_ingest_receipts_source_id'), 'ingest_receipts', ['source_id'], unique=False)
    op.create_table('object_edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('src_id', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=60), nullable=False),
    sa.Column('dst_id', sa.String(length=32), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_edges_dst_id'), 'object_edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_object_edges_relation'), 'object_edges', ['relation'], unique=False)
    op.create_index(op.f('ix_object_edges_src_id'), 'object_edges', ['src_id'], unique=False)
    op.create_table('object_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'name')
    )
    op.create_index(op.f('ix_object_nodes_kind'), 'object_nodes', ['kind'], unique=False)
    op.create_index(op.f('ix_object_nodes_name'), 'object_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_object_nodes_tenant_id'), 'object_nodes', ['tenant_id'], unique=False)
    op.create_table('policy_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_policy_records_status'), 'policy_records', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_kind'), 'recommendations', ['kind'], unique=False)
    op.create_index(op.f('ix_recommendations_tenant_id'), 'recommendations', ['tenant_id'], unique=False)
    op.create_table('relationship_sources',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('collector_identity', sa.String(length=300), nullable=False),
    sa.Column('allowed_namespace', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_sources_tenant_id'), 'relationship_sources', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_sources_tenant_id'), table_name='relationship_sources')
    op.drop_table('relationship_sources')
    op.drop_index(op.f('ix_recommendations_tenant_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_kind'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_policy_records_status'), table_name='policy_records')
    op.drop_table('policy_records')
    op.drop_index(op.f('ix_object_nodes_tenant_id'), table_name='object_nodes')
    op.drop_index(op.f('ix_object_nodes_name'), table_name='object_nodes')
    op.drop_index(op.f('ix_object_nodes_kind'), table_name='object_nodes')
    op.drop_table('object_nodes')
    op.drop_index(op.f('ix_object_edges_src_id'), table_name='object_edges')
    op.drop_index(op.f('ix_object_edges_relation'), table_name='object_edges')
    op.drop_index(op.f('ix_object_edges_dst_id'), table_name='object_edges')
    op.drop_table('object_edges')
    op.drop_index(op.f('ix_ingest_receipts_source_id'), table_name='ingest_receipts')
    op.drop_table('ingest_receipts')
    op.drop_index(op.f('ix_grants_tenant_id'), table_name='grants')
    op.drop_index(op.f('ix_grants_subject'), table_name='grants')
    op.drop_index(op.f('ix_grants_correlation_id'), table_name='grants')
    op.drop_table('grants')
    op.drop_index(op.f('ix_audit_records_tenant_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_subject'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_event'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_correlation_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_action'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_correlation_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_access_nodes_tenant_id'), table_name='access_nodes')
    op.drop_index(op.f('ix_access_nodes_source_id'), table_name='access_nodes')
    op.drop_index(op.f('ix_access_nodes_name'), table_name='access_nodes')
    op.drop_index(op.f('ix_access_nodes_kind'), table_name='access_nodes')
    op.drop_index(op.f('ix_access_nodes_external_id'), table_name='access_nodes')
    op.drop_table('access_nodes')
    op.drop_index(op.f('ix_access_edges_tenant_id'), table_name='access_edges')
    op.drop_index(op.f('ix_access_edges_src_id'), table_name='access_edges')
    op.drop_index(op.f('ix_access_edges_source_id'), table_name='access_edges')
    op.drop_index(op.f('ix_access_edges_relation'), table_name='access_edges')
    op.drop_index(op.f('ix_access_edges_dst_id'), table_name='access_edges')
    op.drop_table('access_edges')
    # ### end Alembic commands ###
