"""Frozen connector synchronization tables."""
from alembic import op
import sqlalchemy as sa
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('fact_key', sa.String(length=80), nullable=False),
    sa.Column('generation', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'fact_key', 'generation')
    )
    op.create_index(op.f('ix_connector_facts_fact_key'), 'connector_facts', ['fact_key'], unique=False)
    op.create_index(op.f('ix_connector_facts_source_id'), 'connector_facts', ['source_id'], unique=False)
    op.create_table('connector_receipts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'sequence')
    )
    op.create_index(op.f('ix_connector_receipts_source_id'), 'connector_receipts', ['source_id'], unique=False)
    op.create_table('connector_states',
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=120), nullable=True),
    sa.Column('coverage', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connector_states')
    op.drop_index(op.f('ix_connector_receipts_source_id'), table_name='connector_receipts')
    op.drop_table('connector_receipts')
    op.drop_index(op.f('ix_connector_facts_source_id'), table_name='connector_facts')
    op.drop_index(op.f('ix_connector_facts_fact_key'), table_name='connector_facts')
    op.drop_table('connector_facts')
    # ### end Alembic commands ###
